export enum OrderListEnum {
    ID = "id",
    _ID = "-id",
    NAME = "name",
    _NAME = "-name",
    SURNAME = "surname",
    _SURNAME = "-surname",
    EMAIL = "email",
    _EMAIL = "-email",
    PHONE = "phone",
    _PHONE = "-phone",
    AGE = "age",
    _AGE = "-age",
    COURSE = "course",
    _COURSE = "-course",
    COURSE_FORMAT = "course_format",
    _COURSE_FORMAT = "-course_format",
    COURSE_TYPE = "course_type",
    _COURSE_TYPE = "-course_type",
    STATUS = "status",
    _STATUS = "-status",
    SUM = "sum",
    _SUM = "-sum",
    ALREADY_PAID = "already_paid",
    _ALREADY_PAID = "-already_paid",
    GROUP = "group",
    _GROUP = "-group",
    CREATED_AT = "created_at",
    _CREATED_AT = "-created_at",
    MANAGER = "manager",
    _MANAGER = "-manager",

}